
export const categoryConstants = {
  CATEGORY_REQURES: 'CATEGORY_REQUEST',
  CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
  CATEGORY_FAILURE: 'CATEGORY_FAILURE',
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE'

}
export const getProductSlugConstants = {
  PRODUCT_REQUEST_SLUG : 'PRODUCT_REQUEST_SLUG',
  PRODUCT_SUCCESS_SLUG : 'PRODUCT_SUCCESS_SLUG',
  PRODUCT_FAILURE_SLUG : 'PRODUCT_FAILURE_SLUG'
}
